### ISSUE TITLE
QM Vermerk: Issue Problematik/ Faulheit (C3) Due: 21.01.

### ISSUE THREAD

**Issue by Greyhound993** [Schmiddl99/experimenteverwaltung-i2#100]

**Comment by TobiasK20** [comment]
@AlenaBischoff ist Aufgabe noch offen?

**Comment by AlenaBischoff** [comment]
Sorry für die Verspätung, leider ist am Wochenende viel Außer der Reihe passiert... :(

Ich habe die Anmerkungen dazu eingetragen :)
