### ISSUE TITLE
Kontrolle: Use Case Model + Use Cases 01-07

### ISSUE THREAD

**Issue by timwuerzburg** [Schmiddl99/experimenteverwaltung-i2#153]

**Comment by TobiasK20** [comment]
- [ ] UC-Model-Seite: _tbd_ entfernen?
- KW als Abkürzung ins Glossar aufgenommen
- [ ] Sicher, dass _Buchungsjournalseite_ ein geeigneter Begriff ist? Reicht nicht Journal (auch durch Glossar)?
- RFs + Co im PR #187
