### ISSUE TITLE
Kontrolle: Iteration Plan 02 & 03

### ISSUE THREAD

**Issue by timwuerzburg** [Schmiddl99/experimenteverwaltung-i2#160]

**Comment by Schmiddl99** [comment]
To Do - Iteration Plan 2:
- [ ] Header mit Namen vervollsändigen
- [ ] Datum des TS-M2 klären
- [ ] LCO Datum fehlt
- [ ] Aufgabenzuordnung - E-Mails und "siehe Issue" durch Namen ersetzen
- [ ] Probleme - Status in "resolved" ändern (Status sollten einheitlich sein)
- [ ] Assessment - "gelbgrün" möglicher Status?! (Vorschlag: gelb)

**Comment by Schmiddl99** [comment]
To Do - Iteration Plan 3:
- [ ] Aufgabenzuordnung - E-Mails durch Namen ersetzen; Due Date bei #77 hinzufügen
- [ ] Probleme - Status in "resolved" ändern (Status sollten einheitlich sein)
- [ ] Assessment - "gelbgrün" möglicher Status?! (Vorschlag: gelb)
- [ ] Assessment - "Nein – 4 Use Cases ausgearbeitet, Rest nur erfasst, adocs liegen vor" - wurde das beim Copy-Paste vergessen?
- [ ] Retrospective - selber Inhalt wie bei IP2?!

**Comment by TobiasK20** [comment]
> * [ ]  Header mit Namen vervollsändigen
Meinst du die Überschrift? Sollte sich it #183 geklärt haben

> * [ ]  LCO Datum fehlt
Der wurde in I2 nicht erreicht

> * [ ]  Assessment - "gelbgrün" möglicher Status?! (Vorschlag: gelb)
Definitionsfrage. Gebe ich den anderen PM in die Diskussion. Im Assessment gab es dazu keine Beanstandungen.

Danke für die weiteren Hinweise! Mache mich morgen dran :)

**Comment by Schmiddl99** [comment]
> * [ ]   Header mit Namen vervollsändigen
>   Meinst du die Überschrift? Sollte sich it #183 geklärt haben

Ich schätze mal, du meinst, dass sich das in #180 geklärt hat ^^

> * [ ]   LCO Datum fehlt
>   Der wurde in I2 nicht erreicht

OK

> * [ ]   Assessment - "gelbgrün" möglicher Status?! (Vorschlag: gelb)
>   Definitionsfrage. Gebe ich den anderen PM in die Diskussion. Im Assessment gab es dazu keine Beanstandungen.

Ich fand das iwie zu uneindeutig. Auf Arbeit verwenden wir halt auch nur grün, gelb, rot
 
> * [ ]  Probleme - Status in "resolved" ändern (Status sollten einheitlich sein)
>   Wo haben wir denn resolved genutzt? Denglisch würde ich jetzt nicht einführen wollen.

Im Board "Iteration Plan" haben wir die Spalte mit dem Status "Resolved" und an diese Status würde ich mich halten

**Comment by TobiasK20** [comment]
Wenn das mit dem Header jetzt so passt, bin ich mit IP02 durch

**Comment by Schmiddl99** [comment]
Bitte schaut noch einmal drüber, da es einen Merge mit Main, außerhalb dieses Branches, gab!

Daher nochmal Obacht an zukünftige Commits bei unterschiedlich bearbeiteten Branches! Ich habe das vorhin noch mit Richard auseinanderpflücken müssen, weil das so verwirrend war.
