### ISSUE TITLE
GitHub Konvention: Regeln ausarbeiten (B1) DUE: 15.12.

### ISSUE THREAD

**Issue by TobiasK20** [Schmiddl99/experimenteverwaltung-i2#19]
Wiki pflegen!
+Taejun

**Comment by richardboehme** [comment]
@TobiasK20 Kannst du das Issue in TODO (bzw. Work in Progress) direkt verschieben?

**Comment by richardboehme** [comment]
Konventionen sind [hier](../wiki/Github-Regeln) dokumentiert.
