### ISSUE TITLE
Hinweise zum Repository

### ISSUE THREAD

**Issue by tigion** [Schmiddl99/experimenteverwaltung-i2#2]
Nicht vergessen, dass Repository soll im Beleg als **zentrale** Ablage für alle **Teammitglieder** und uns **Coaches** dienen, sodass jeder jederzeit auf den aktuellen Projektstand zugreifen kann. Idealerweise gibt es jemanden im Team, welcher ein Auge auf das Repository hat und den Anderen helfen kann. Fragen zu Git, GitHub und Asciidoctor gern auch an mich.

Ein paar Vorschläge:

- Bitte Gedanken über eine passende Projektstruktur für die zu erstellenden Dokumente, Quellcodes und anderen Fragmente im Repository machen. Am einfachsten wäre es die Vorlage [Projektstruktur_OpenUP-Templates](https://github.com/htwdd-se/Projektstruktur_OpenUP-Templates) zu übernehmen.
- Projektbeschreibung anpassen (README.md), bzw. eine neue anlegen und die alte unter einem angepassten Namen speichern.
- Lizenz prüfen und ggf. anpassen, ob sie für das ganze Projekt gelten soll, da nur die Templates aus der Vorlage [Projektstruktur_OpenUP-Templates](https://github.com/htwdd-se/Projektstruktur_OpenUP-Templates) unter der CC-BY-4.0 Lizenz stehen. Hier entsprechend in der README.md einen Hinweis wie folgt aufnehmen:

  > Die Dokumentation enthält Vorlagen aus dem [Projektstruktur_OpenUP-Templates](https://github.com/htwdd-se/Projektstruktur_OpenUP-Templates) Repositorie, welches Templates unter der [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/) Lizenz enthält.

- Anstehende Aufgaben können, alternativ zu anderen Tools, über **Issues** zum Projekt und in Projekten (bspw. für Iterationen) verwaltet werden.

**Comment by TobiasK20** [comment]
Unser repo bekommt nun nach und nach Struktur. Die Vorlage wird step-by-step für Belegbestandteile übernommen und ausgefüllt. Die Lizenz wurde in der readme.md erwähnt. Aufgaben werden nun, nach Erarbeitung eines Aufgaben-Verwaltungs-Boards "Iteration Planning" (https://github.com/Schmiddl99/experimenteverwaltung-i2/projects/3), als Issues verwaltet.

Danke @tigion für die initialen Hinweise!
