### ISSUE TITLE
Programmierkonvention erstellen (B2)

### ISSUE THREAD

**Issue by Greyhound993** [Schmiddl99/experimenteverwaltung-i2#216]

**Comment by richardboehme** [comment]
Hallo Gregor, folgendes habe ich kurz zusammengefasst. Hoffe das ist soweit ausreichend:

Alle Entwickler halten sich an die folgenden Programmierkonventionen. Diese wurden aus den Konventionen der Ruby-Community entnommen und gewählt, um eine gewisse Qualität des Codes zu gewährleisten. Dies hilft dabei den Code übersichtlich zu halten und trägt zur einfacheren Wartbarkeit und Weiterentwicklung der Anwendung bei.

* Code (Variablen, Klassennamen usw.) und Kommentare werden in Englisch geschrieben.
* Jeder hält sich grob an den Ruby Styleguide (https://github.com/rubocop/ruby-style-guide).
* Funktionen und Klassen werden mithilfe des Tools Yard dokumentiert (https://yardoc.org).
* Es wird versucht sich an die Standards und Konventionen von Rails zu halten.
