### ISSUE TITLE
Projektname in den AsciiDoc Dokumenten

### ISSUE THREAD

**Issue by tigion** [Schmiddl99/experimenteverwaltung-i2#30]
In der Datei *.../_includes/default-attributes.inc.adoc* kann im Attribut **:project-name:** der Projektname gesetzt werden, aber bitte ohne die Platzhaltersymbole `<>` und `{}`. Dieser wird dann automatisch in allen Dokumenten beim Generieren im Titel entsprechend ersetzt:

Bspw.:
```
:project-name: Verwaltung von Physikexperimenten (I2)
```

Wenn Sie Ihre Dokumente losgelöst von der Projektstruktur der Vorlage bearbeiten, denken Sie bitte daran die entsprechenden Pfade in Ihren Dokumenten und dem Belegabgabedokument zu den einzubindenden Dateien (includes) anzupassen:
- `_includes/default-attributes.inc.adoc` in den Dokumenten (globalen Attribute, welche über alle Dokumente gleich sind)
- In der *se1_belegabgabe_tI2.adoc* beziehen sich alle Verweise ebenfalls auf die Vorlagenstruktur.

**Comment by TobiasK20** [comment]
Ja, das hängt wie eben festgestellt noch in einer pull request fest. Ich informiere Sie zu gegebenem Zeitpunkt, wenn sie die Änderungen auch im main branch finden. Bitte entschuldigen Sie die Unstimmigkeit, das war mir selbst nicht bewusst.

**Comment by tigion** [comment]
In die Pull-Request Branches kann ich zwar auch anschauen, aber ich weiß nicht, ob diese Änderung so in Ihr Projekt übernommen wird bzw. noch angepasst wird.

Generell sollten Änderungen nicht zu lange in den Pull-Requests hängen bzw. nur neue Änderungen enthalten. Sonst liegen alle Projekt relevanten Informationen verstreut auf Pull-Requests und im eigentliche Repository liegt ein zu veralteter Stand. Fortlaufen geändert darf ja trotzdem an den Dokumenten werden.
