### ISSUE TITLE
QM: Git-Konvention (C3) DUE: 30.12.

### ISSUE THREAD

**Issue by TobiasK20** [Schmiddl99/experimenteverwaltung-i2#34]
Bitte Pull-request-system etc. in QM-Handbuch übernehmen
Im Anschluss an den Git-Workshop

**Comment by AlenaBischoff** [comment]
@TobiasK20 
Gibt es zu dem Pull-Request System eine schriftliche... Abhandlung die Bereits erstellt wurden? Wenn ja, wo finde ich die?
Das Erklärbär Video würde ich in der Dokumentation ebenfalls mit anfügen. Haben wir eine Möglichkeit, das zu Downloaden und im GitHub für eine Verlinkung / Zugriff bereitzustellen? (Oder ist das bereits schon passiert?)

**Comment by TobiasK20** [comment]
https://github.com/Schmiddl99/experimenteverwaltung-i2/wiki/Github-Regeln m.E. die einzige Niederschrift dazu. Das Video kann über Teams heruntergeladen werden; finde das Verlinken eine sehr gute Idee! Denke aber nicht dass das ins Repo sollte. Siehe Nachricht WhatsApp

**Comment by AlenaBischoff** [comment]
QM Dokument wurde ergänz.
@TobiasK20 Soll das ganze schon in das GitHub übernommen werden? Habe es erstmal nur im Teams gemacht.
Wenn ja, bitte "QM Dokument zu ASCII-DOC umformen" als Issue aufnehmen.
