### ISSUE TITLE
Log-In-Vergabe recherchieren und Entscheidung treffen (B2)

### ISSUE THREAD

**Issue by TobiasK20** [Schmiddl99/experimenteverwaltung-i2#45]
Prüfung ob eigener Login entwickelt werden muss oder der von der HTW interne verwendet werden kann

**Comment by richardboehme** [comment]
Hey Tobias, kannst du mir genauer erklären was hier zu tun ist? Was wir wissen: Die Logins können von allen Admin Accounts angelegt werden, wobei ein Nutername, ein Passwort und eine Rolle vergeben werden können. Zudem kann man den Account deaktivieren/aktivieren. Geht es hier darum, dass aus datenschutzrechtlicher Sicht die Vergabe eines Passworts durch Herr Heisig für die Dozenten nicht in Ordnung ist?

**Comment by TobiasK20** [comment]
Ja, die Aufgabe wird später (nicht in dieser Iteration) relevant. In TS-M2 mit Herrn Heisig haben wir über die Datenschutzproblematik gesprochen (siehe Protokoll). Der Login wird den Dozenten (PW+Nutzername) individuell zugeteilt. Was müssen wir datenschutzrechtlich beachten? Diese Architekturfrage wurde hier erstmal in der Work Item List festgehalten :)
Fragen dazu gern im weekly.
