### ISSUE TITLE
Dok: Zugänge (Anwendung, VM...) in Teams anlegen (C3) DUE:31.12.

### ISSUE THREAD

**Issue by TobiasK20** [Schmiddl99/experimenteverwaltung-i2#57]

**Comment by richardboehme** [comment]
Hey @TobiasK20 @timwuerzburg, ich habe mal die Datei, mit allen mir bekannten Zugängen, angelegt. Sie liegt unter weitere Dokumente -> Zugänge im Teams. Fallen euch noch welche ein?

**Comment by TobiasK20** [comment]
Sehr gut @richardboehme. Mir fallen gerade keine weiteren ein.

**Comment by TobiasK20** [comment]
Habe noch den Zugang zu dem ESSENCE-Tool ergänzt (Ansprechpartner Prof. Anke) @richardboehme
