### ISSUE TITLE
WF-PPT unabhängig vom Meeting Frau Krawietz zukommen lassen (B2) DUE: 21.01.

### ISSUE THREAD

**Issue by TobiasK20** [Schmiddl99/experimenteverwaltung-i2#93]
Siehe vorbereitete Mails

**Comment by AlenaBischoff** [comment]
WF wurden nach aktuellem Wissenstand und Absprachen angepasst. (siehe Teams)
@TobiasK20 du kannst gerne die neuen Verwenden und an Frau Krawietz senden.

**Comment by TobiasK20** [comment]
Gut, sprechen wir morgen im Weekly nochmal drüber. Anmerkung siehe Teams :)
